method: random
metric:
  name: val_PSNR
  goal: maximize
parameters:
  first_kernel:
    values: [3, 5, 7]
  outer_kernel:
    values: [3, 5, 7]
  middle_kernel:
    values: [3, 5, 7]
  last_kernel:
    values: [3, 5, 7]
